name: Fix Code Style (Python)

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.LINTER_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Run Ruff (auto-fix)
        run: ruff check ismr_downloader --fix

      - name: Run Black (auto-format)
        run: black ismr_downloader

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix Python lint issues"